replace patchesStrategicMerge with patches
GoogleCloudPlatform/microservices-demo pull request #1689
Opened 2023-04-12 17:06 UTC by smeet07

### Background 

### Fixes 
#1564

### Change Summary

### Additional Notes

### Testing Procedure

### Related PRs or Issues

2023-04-13 15:00 UTC, smeet07 commented
R: @NimJay

2023-04-13 19:28 UTC, bourgeoisor commented
This pipeline is failing: https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/.github/workflows/kustomize-build-ci.yaml

@smeet07 could look into this + add some more context in the description?

2023-04-13 20:08 UTC, smeet07 commented
> This pipeline is failing: https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/.github/workflows/kustomize-build-ci.yaml
> 
> @smeet07 could look into this + add some more context in the description?

The patchesStrategicMerge has been deprecated and hence needs to be replaced by patches

2023-04-18 18:42 UTC, smeet07 commented
@NimJay

2023-04-19 21:51 UTC, minherz requested changes

2023-04-19 21:51 UTC, minherz commented on kustomize/components/cymbal-branding/kustomization.yaml
> +  - |-
there is extra indentation that breaks the format. Please shift left _all_ content under `patches`

2023-04-19 21:52 UTC, minherz commented
@NimJay , you probably will need to fix the problem with the required code-tests and deployment-tests checks using the [recommended technique][1].

[1]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

2023-04-19 23:31 UTC, minherz reviewed
the syntax for `patches` is incorrect. The problem is not only in the cymbal-branding component but in all components that have inline patch.
See [examples] for inline patching. TL;DR; you need to define a field `patch:` for each element of the `patches` list.

I fixed it for you.

[examples]: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md

2023-04-19 23:38 UTC, merged