feat: add support for baseUrl
GoogleCloudPlatform/microservices-demo pull request #2609
Opened 2024-06-25 12:03 UTC by aslafy-z

### Background 

I want to host this microservice demo frontend on a subpath (`X.X.X.X/online-boutique/`). I made my reverse proxy rewrite the url by removing `/online-boutique` from the paths it sees. However, the frontend html pages uses absolute urls which cannot be solved with the reverse proxy. 
### Fixes 

### Change Summary

- Add baseUrl from BASE_URL environment variable to default template variables
- Add <base href=baseUrl> tag to header
- Add baseUrl to XHR calls

### Additional Notes

### Testing Procedure

### Related PRs or Issues

2024-06-26 11:26 UTC, aslafy-z commented on src/frontend/main.go
> +	r.PathPrefix(baseUrl + "/static/").Handler(http.StripPrefix("/static/", http.FileServer(http.Dir("./static/"))))
```suggestion
	r.PathPrefix(baseUrl + "/static/").Handler(http.StripPrefix(baseUrl + "/static/", http.FileServer(http.Dir("./static/"))))
```
```suggestion
	r.PathPrefix(baseUrl + "/static/").Handler(http.StripPrefix("/static/", http.FileServer(http.Dir("./static/"))))
```

2024-06-27 18:49 UTC, NimJay requested changes
Thanks for this feature.

It looks like the "You May Also Like" section of each product page is broken in the staging URL:
<img width="1256" alt="Screenshot 2024-06-27 at 2 48 12 PM" src="https://github.com/GoogleCloudPlatform/microservices-demo/assets/10292865/44950024-4ccf-4c66-a571-306e278553a1">

Do you know if it might be due to a change in the .html templates?

2024-07-02 15:39 UTC, aslafy-z commented
@NimJay I don't think so, the same changes were done on the product listing page without issue: https://github.com/GoogleCloudPlatform/microservices-demo/pull/2609/files#diff-486e203835857587dcd0bd356e4778094d7514a853fcfb8d83b6c0163b471eaeL48-L49.

2024-07-02 17:14 UTC, aslafy-z commented
I updated the code to fix Ad and Recommendation templates. I had to pass them the global context. I'm not a fan of that solution, however, it works well.
I pushed an updated image at `docker.io/zadki3l/microservice-demo-frontend:v0.11.0-dev.4`.

2024-07-22 15:08 UTC, NimJay approved these changes

2024-07-22 15:08 UTC, merged