Bumped the urllib3 and requests modules from dependabot alerts
GoogleCloudPlatform/microservices-demo pull request #695
Opened 2022-01-24 22:20 UTC by ckim328

### Background 
Dependabot alerts for urllib3 indicating `high severity` in our email and recommendation service
### Fixes 
Relevant CVE description [here](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503)

### Change Summary
I bumped the urllib3 module to 1.26.5 and had to bump the requests module (to v2.27.1) as well to accommodate the bump

### Additional Notes
n/a

### Testing Procedure
Tested it locally, images built, and worked as expected!

### Related PRs or Issues 
n/a

2022-01-24 22:30 UTC, bourgeoisor requested changes
I don't see any changes to the `requirements.in` files; were the changes to the `requirements.txt` files made manually? We shouldn't touch those directly and instead use the `.in` as input to `pip-compile`. The reason we want to do this is for transitive-dependency purposes. e.g. bumping `requests` or `urllib3` might in turn bump some transitive dependency requirements. Rather than chase them manually, you just let `pip-compile` do it for you!

2022-01-24 22:56 UTC, ckim328 commented
Oh yes! I will update accordingly!!
Thanks for the reminder @bourgeoisor  🐐 👍

2022-01-25 17:59 UTC, NimJay approved these changes
Thanks for address these 2 Dependabot alerts — even [ loadgenerator](https://github.com/GoogleCloudPlatform/microservices-demo/security/dependabot/src/loadgenerator/requirements.txt/urllib3/closed)!

Changes look good to me — seems like the `requirements.txt` files are now untouched.

I did a quick smoke test of the staging URL. Looks good.

2022-01-25 19:51 UTC, bourgeoisor approved these changes
LGTM!

2022-01-25 20:20 UTC, merged