Feat: Implement Memorystore (Redis) Deployment Variation with Online Boutique
GoogleCloudPlatform/microservices-demo pull request #949
Opened 2022-08-10 14:22 UTC by jaspermai

This Pull Request introduces the Memorystore (Redis) Deployment variant of Online Boutique. The deployment uses Terraform to implement infrastructure changes and shell/Kustomize to implement configuration changes.

# Background 
[Online Boutique (microservices-demo)](https://github.com/GoogleCloudPlatform/microservices-demo) is a sample web application that simulates a web-based e-commerce application for users to browse items, add them to cart, and purchase them. The sample application demonstrates using an 11-tier microservices application deployed using Kubernetes/GKE.

In addition to the vanilla deployment of Online Boutique, the sample application supports various deployment options that allow users to introduce debugging, styling, and infrastructure changes to their version of the sample application. The complete list of deployment options can be found [here](https://github.com/GoogleCloudPlatform/microservices-demo) in the Other Deployment Options section of the README.

This PR supports the automation of a third deployment option ([Memorystore](https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/docs/memorystore.md)) and showcases how the existing Online Boutique repo should be used with Terraform & Kustomize.

# Summary of Changes
- Repo updates (updated variables file, updated main.tf, new Terraform file, new Kustomize file)
- What Memorystore does to the deployment
- Deployment steps will require users to change new Kustomize fille

# Deploy Memorystore (Redis)
- Make sure you have the repo setup. For simplicity, recommended use the built-in Terraform setup with Online Boutique. Note that you don't have to have a running deployment. You can just follow the steps below as Terraform step will take care of the deployment. 
- Changes variables, enable to true

## Run the deployment options

## Cleanup
- Kustomize, Terraform

## Testing
- Make sure shopping cart works

2022-08-10 18:17 UTC, mathieu-benoit commented
Really great content here, great job @jaspermai!

Out of curiosity, anything avoiding you to do these steps below in Terraform (instead of asking the end users to run the commands)?
![image](https://user-images.githubusercontent.com/11720844/183986727-b0859ea2-be0a-4c03-8b48-68d7129c7faf.png)
Typically, you could add a new `null_resource` waiting for Memorystore to be provisioned with a `local_exec` with these commands.

2022-08-10 18:52 UTC, NimJay commented
@mathieu-benoit That's a great point you raise (i.e., should we use Terraform for setting the Memory IP address inside the YAML instead of asking the user to run a `sed` command). I am open to putting that logic inside Terraform too. Whether we do it inside this PR is up to @ahrarmonsur and @jaspermai. :)

**Related issue:** Should Terraform stick to infrastructure logic — and not stay away from deployment logic?
The logic we'd be adding to Terraform is more related to deployment than infrastructure.
@bourgeoisor pointed out a philosophy for using Terraform in this [Google Doc comment thread](https://docs.google.com/document/d/1ANqESJUPK49V1Yb6u33Sr1tJhrfKOpF7KgPJZgq8Asc/edit?resourcekey=0-tbS21ZElkw64VXjNzQIvYA&disco=AAAAdQrUx2I): Terraform's sole responsibility should be provisioning infrastructure.
@mathieu-benoit I'd love to hear your thoughts around this.

2022-08-10 19:11 UTC, mathieu-benoit commented
@NimJay, agree with the fact that there is better ways to deploy apps/manifests rather than having this part in Terraform. But I think that's ok for the purpose of this "one-click" deployment approach with Terraform we are taking. Actually, that's already what we are doing by deploying the Kubernetes manifests in Terraform: https://github.com/GoogleCloudPlatform/microservices-demo/blob/main/terraform/main.tf#L76. So doing this for the Kustomize/sed part by injecting an Infrastructure infromation (Redis IP) is aligned with that too.

2022-08-10 19:21 UTC, NimJay requested changes
This is looking good!
I added some preliminary comments — I have yet to test out the steps myself.

2022-08-10 19:21 UTC, NimJay commented on kustomize/kustomization.yaml
> +  - components/memorystore
**Question:**
Was this change intentional?
I think, by default, `kustomize/kustomization.yaml` should not use `components/memorystore`.
Feel free to ignore — not a deal breaker.

2022-08-10 19:21 UTC, NimJay commented on terraform/main.tf
> +  base_apis = [
Praise: Thanks for updating the name of this array to `base_apis`.

2022-08-11 15:15 UTC, jaspermai commented
> Using `null_resource` in Terraform to automade the `sed` command.

@mathieu-benoit That's a very valid suggestion that I didn't think about! I agree with you that since the Terraform is automating the manifest apply step, we might as well automate the infrastructure information injection step. For the time-being I'll have that change reflected in this PR.

2022-08-12 19:53 UTC, ahrarmonsur requested changes

2022-08-12 19:53 UTC, ahrarmonsur commented on kustomize/components/memorystore/kustomization.yaml
> +
Nit: Add empty line at the end of all the files
.

2022-08-12 19:53 UTC, ahrarmonsur commented on terraform/main.tf
> +  # activate_apis is defined as base_apis and memorystore_apis if memorystore is enabled
Praise: I am glad this dynamic API list creation works as we discussed! It makes for a much cleaner solution and far fewer TF resource blocks! Great job, Jasper!

Suggestion: The comment should be made much more generalized while still explaining what's being done. We should have not to update this for every variant we add.

Alternative: "`activate_apis` is the set of `base_apis` and the APIs required by user-configured deployment options."

2022-08-12 19:53 UTC, ahrarmonsur commented on terraform/memorystore.tf
> +  region         = var.region_memorystore
I would suggest we use the same region as the core app (defined as the "region" variable) for the Memorystore deployment. Having them separated does not provide enough illustrative value for our sample.

2022-08-12 19:53 UTC, ahrarmonsur commented on terraform/variables.tf
> +variable "region_memorystore" {
I believe this is not necessary, and we should reuse the "region" variable, instead.

2022-08-14 18:21 UTC, NimJay commented on kustomize/kustomization.yaml
> +  # - components/memorystore
Praise: I like that you've commented out all components by default. And you've included all components (in alphabetical order). 👌

2022-08-14 18:29 UTC, NimJay commented on terraform/memorystore.tf
> +}
```suggestion
}

```

2022-08-14 18:29 UTC, NimJay commented on terraform/memorystore.tf
> +}
(as per Ahrar's suggestion)

2022-08-14 18:29 UTC, NimJay commented on terraform/variables.tf
> +}
```suggestion
}

```
as per Ahrar's suggestion

2022-08-14 19:18 UTC, NimJay approved these changes
I tried out the Terraform with `memorystore = true`, and it successfully provisioned the GKE cluster and Memorystore Redis cache. And it replaced the `REDIS_IP` variable with the Memorystore IP address. 👍 Looks good.

<img width="294" alt="Screen Shot 2022-08-14 at 2 56 30 PM" src="https://user-images.githubusercontent.com/10292865/184551352-488fed8f-b325-4d0d-897c-2b418d981320.png">

I also tested `kubectl apply -k kustomize/kustomization.yaml` with `components/memorystore`.
I was able verify that Online Boutique was using the Memorystore cache, by deleting the `redis-cart` `Service` and `Deployment`, and checking that Online Boutique still works (i.e., the cart is functional):
```
kubectl delete service redis-cart
kubectl delete deployment redis-cart
# Online Boutique still worked!
```

If time (left for your internship) permits, we could update the Terraform to (outside of this PR):
- conditionally uncomment `# - components/memorystore` (if `memorystore = true`)
- set the default value of `filepath_manifest` to `kustomize/kustomization.yaml`
- use `kubectl apply -k ${var.filepath_manifest}` instead of `kubectl apply -f ${var.filepath_manifest}`

You have my approval for this pull-request! Great job once again, Jasper! 👏

2022-08-15 15:57 UTC, ahrarmonsur approved these changes
Thank you very much for addressing my comments, @jaspermai! This is looking good!
I also tested the deployment, and was succcessful!

LGTM!

2022-08-15 17:21 UTC, merged